"use client";

import React, { useState } from "react";
import {
  Brain,
  ChevronLeft,
  RefreshCw,
  Check,
  X,
  Sparkles,
  BookOpen,
  ArrowRight,
  HelpCircle,
  Trophy
} from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

interface Flashcard {
  id: string;
  front: string;
  back: string;
  sourceQuestion?: string;
}

interface FlashcardDeck {
  id: string;
  topicName: string;
  cardCount: number;
  lastStudied: string;
  mastery: number; // percentage
  cards: Flashcard[];
}

const mockDecks: FlashcardDeck[] = [
  {
    id: "deck-1",
    topicName: "Process Synchronization",
    cardCount: 5,
    lastStudied: "2 days ago",
    mastery: 60,
    cards: [
      {
        id: "fc-1-1",
        front: "What is the primary objective of mutual exclusion?",
        back: "To prevent multiple processes from simultaneously entering their critical sections, preventing race conditions on shared resources.",
        sourceQuestion: "What is the critical section problem? Detail the three requirements...",
      },
      {
        id: "fc-1-2",
        front: "What are the two standard operations of a semaphore?",
        back: "wait() [or P()] which decrements the semaphore, and signal() [or V()] which increments the semaphore. Both are atomic.",
        sourceQuestion: "Define mutual exclusion and discuss how semaphores...",
      },
      {
        id: "fc-1-3",
        front: "Explain the difference between a spinlock and a blocking semaphore.",
        back: "Spinlocks keep a process in busy-wait (wasting CPU cycles) while waiting for lock. Blocking semaphores suspend the process, putting it to sleep in a queue.",
        sourceQuestion: "Define mutual exclusion and discuss how semaphores...",
      },
      {
        id: "fc-1-4",
        front: "What is a race condition?",
        back: "A scenario where multiple processes access and manipulate the same shared data concurrently, making the outcome dependent on the execution order.",
        sourceQuestion: "What is the critical section problem? Detail the three...",
      },
      {
        id: "fc-1-5",
        front: "State the three requirements for a valid critical section solution.",
        back: "1. Mutual Exclusion\n2. Progress\n3. Bounded Waiting",
        sourceQuestion: "What is the critical section problem? Detail the three...",
      },
    ],
  },
  {
    id: "deck-2",
    topicName: "Database Normalization",
    cardCount: 3,
    lastStudied: "Yesterday",
    mastery: 80,
    cards: [
      {
        id: "fc-2-1",
        front: "Define 1st Normal Form (1NF).",
        back: "A relation is in 1NF if and only if all domain values are atomic (no repeating groups or multi-valued attributes).",
        sourceQuestion: "Given a schema R(A, B, C, D, E) with functional...",
      },
      {
        id: "fc-2-2",
        front: "What is the key requirement for 2nd Normal Form (2NF)?",
        back: "It must be in 1NF, and all non-key attributes must be fully functionally dependent on the primary key (no partial dependencies).",
        sourceQuestion: "Given a schema R(A, B, C, D, E) with functional...",
      },
      {
        id: "fc-2-3",
        front: "Define 3rd Normal Form (3NF).",
        back: "It must be in 2NF, and no non-key attribute is transitively dependent on the primary key (no X -> Y -> Z dependencies).",
        sourceQuestion: "Given a schema R(A, B, C, D, E) with functional...",
      },
    ],
  },
  {
    id: "deck-3",
    topicName: "Memory Management",
    cardCount: 4,
    lastStudied: "Not studied yet",
    mastery: 0,
    cards: [
      {
        id: "fc-3-1",
        front: "What is logical address vs physical address?",
        back: "Logical address is generated by the CPU during execution. Physical address is the actual location in the memory hardware unit.",
      },
      {
        id: "fc-3-2",
        front: "What is the role of the MMU (Memory Management Unit)?",
        back: "A hardware device that handles run-time mapping of logical virtual addresses to physical memory addresses.",
      },
    ],
  },
];

export default function FlashcardsPage() {
  const [decks, setDecks] = useState<FlashcardDeck[]>(mockDecks);
  const [activeDeck, setActiveDeck] = useState<FlashcardDeck | null>(null);
  const [currentCardIdx, setCurrentCardIdx] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [knownCardsCount, setKnownCardsCount] = useState(0);
  const [showSummary, setShowSummary] = useState(false);

  const startDeckStudy = (deck: FlashcardDeck) => {
    setActiveDeck(deck);
    setCurrentCardIdx(0);
    setIsFlipped(false);
    setKnownCardsCount(0);
    setShowSummary(false);
  };

  const handleCardFeedback = (isKnown: boolean) => {
    if (isKnown) {
      setKnownCardsCount((prev) => prev + 1);
    }

    setIsFlipped(false);

    // Short timeout to let card rotate back before moving to next
    setTimeout(() => {
      if (activeDeck && currentCardIdx < activeDeck.cards.length - 1) {
        setCurrentCardIdx((prev) => prev + 1);
      } else {
        setShowSummary(true);
      }
    }, 200);
  };

  const handleRestartDeck = () => {
    setCurrentCardIdx(0);
    setIsFlipped(false);
    setKnownCardsCount(0);
    setShowSummary(false);
  };

  const handleFinishDeck = () => {
    if (activeDeck) {
      const finalMastery = Math.round((knownCardsCount / activeDeck.cards.length) * 100);
      setDecks(
        decks.map((d) =>
          d.id === activeDeck.id
            ? { ...d, mastery: finalMastery, lastStudied: "Just now" }
            : d
        )
      );
    }
    setActiveDeck(null);
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Styles for 3D card flip */}
      <style jsx global>{`
        .perspective-1000 {
          perspective: 1000px;
        }
        .preserve-3d {
          transform-style: preserve-3d;
        }
        .backface-hidden {
          backface-visibility: hidden;
        }
        .rotate-y-180 {
          transform: rotateY(180deg);
        }
      `}</style>

      {/* Title bar */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-slate-800 dark:text-zinc-50 flex items-center gap-2">
            <Brain className="h-6 w-6 text-violet-500" />
            Flashcard Decks
          </h2>
          <p className="text-sm text-slate-500 dark:text-zinc-400 mt-1">
            Revise key terms and concepts using active recall flashcards.
          </p>
        </div>
        {activeDeck && (
          <Button
            variant="ghost"
            onClick={handleFinishDeck}
            className="rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 text-xs font-semibold"
          >
            <ChevronLeft className="h-4 w-4 mr-1" />
            Exit Study
          </Button>
        )}
      </div>

      {/* MAIN VIEW */}
      {!activeDeck ? (
        /* List Decks Grid */
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {decks.map((deck) => (
            <Card
              key={deck.id}
              className="border-slate-200/50 dark:border-zinc-800/50 shadow-sm hover:shadow-md transition-all duration-300 bg-white/70 dark:bg-zinc-950/70 backdrop-blur-md flex flex-col group relative overflow-hidden"
            >
              <div className="absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r from-violet-600 to-teal-500 opacity-0 group-hover:opacity-100 transition-opacity" />
              <CardHeader>
                <div className="flex justify-between items-start">
                  <Badge variant="secondary" className="rounded-md font-bold px-2 py-0.5 text-[9px] bg-violet-500/10 text-violet-600 dark:text-violet-400 border-none uppercase pointer-events-none">
                    {deck.cardCount} cards
                  </Badge>
                  <span className="text-[10px] text-slate-400 dark:text-zinc-500 font-semibold flex items-center gap-1">
                    Studied {deck.lastStudied}
                  </span>
                </div>
                <CardTitle className="text-base font-extrabold text-slate-800 dark:text-zinc-100 mt-3 group-hover:text-violet-600 dark:group-hover:text-violet-400 transition-colors">
                  {deck.topicName}
                </CardTitle>
                <CardDescription className="text-xs">
                  Review concepts from your uploaded papers
                </CardDescription>
              </CardHeader>
              <CardContent className="flex-1 flex flex-col justify-end space-y-4 pt-0">
                <div className="space-y-1">
                  <div className="flex justify-between text-[11px] font-semibold text-slate-500">
                    <span>Topic Mastery</span>
                    <span>{deck.mastery}%</span>
                  </div>
                  <Progress value={deck.mastery} className="h-1.5 rounded-full bg-slate-100 dark:bg-zinc-900 overflow-hidden" />
                </div>
                <Button
                  onClick={() => startDeckStudy(deck)}
                  className="w-full h-10 rounded-xl bg-slate-50 dark:bg-zinc-900/60 hover:bg-violet-600 dark:hover:bg-violet-600 border border-slate-200 dark:border-zinc-800 hover:border-transparent text-slate-700 dark:text-zinc-300 hover:text-white dark:hover:text-white font-medium group transition-all"
                >
                  Start Studying
                  <ArrowRight className="h-4 w-4 ml-1.5 transition-transform group-hover:translate-x-1" />
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : showSummary ? (
        /* Study Complete Summary View */
        <div className="max-w-md mx-auto">
          <Card className="border-slate-200/50 dark:border-zinc-800/50 shadow-lg bg-white/70 dark:bg-zinc-950/70 backdrop-blur-md text-center p-6 space-y-6">
            <div className="mx-auto h-16 w-16 rounded-full bg-gradient-to-tr from-violet-600 to-teal-500 flex items-center justify-center text-white shadow-lg shadow-violet-500/20">
              <Trophy className="h-8 w-8 animate-bounce-subtle" />
            </div>
            <div>
              <CardTitle className="text-xl font-black">Deck Completed!</CardTitle>
              <CardDescription className="text-xs mt-1">
                You successfully reviewed all cards in <strong>{activeDeck.topicName}</strong>.
              </CardDescription>
            </div>

            <div className="p-4 rounded-2xl bg-slate-50 dark:bg-zinc-900/40 border border-slate-100 dark:border-zinc-800/30 space-y-3">
              <div className="flex justify-between text-xs font-semibold text-slate-600 dark:text-zinc-400">
                <span>Total Cards:</span>
                <span>{activeDeck.cards.length}</span>
              </div>
              <div className="flex justify-between text-xs font-semibold text-slate-600 dark:text-zinc-400">
                <span>Got on first try:</span>
                <span className="text-emerald-600 dark:text-emerald-400">{knownCardsCount} ({Math.round((knownCardsCount / activeDeck.cards.length) * 100)}%)</span>
              </div>
              <div className="flex justify-between text-xs font-semibold text-slate-600 dark:text-zinc-400">
                <span>Study Session Duration:</span>
                <span>~ 1.5 mins</span>
              </div>
            </div>

            <div className="flex gap-3">
              <Button
                variant="outline"
                onClick={handleRestartDeck}
                className="flex-1 h-11 rounded-xl bg-white dark:bg-zinc-950 border-slate-200 dark:border-zinc-800"
              >
                <RefreshCw className="h-4 w-4 mr-2" />
                Study Again
              </Button>
              <Button
                onClick={handleFinishDeck}
                className="flex-1 h-11 rounded-xl bg-gradient-to-r from-violet-600 to-teal-500 hover:from-violet-700 hover:to-teal-600 text-white font-medium shadow-md shadow-violet-500/10"
              >
                Done
              </Button>
            </div>
          </Card>
        </div>
      ) : (
        /* Active Flashcard Player */
        <div className="max-w-2xl mx-auto space-y-6">
          {/* Deck progress indicator */}
          <div className="flex justify-between items-center text-xs text-slate-500 dark:text-zinc-400 font-semibold">
            <span>Reviewing: {activeDeck.topicName}</span>
            <span>Card {currentCardIdx + 1} of {activeDeck.cards.length}</span>
          </div>
          <Progress
            value={((currentCardIdx) / activeDeck.cards.length) * 100}
            className="h-2 rounded-full bg-slate-100 dark:bg-zinc-900 overflow-hidden"
          />

          {/* 3D Card Container */}
          <div
            onClick={() => setIsFlipped(!isFlipped)}
            className="relative h-[320px] w-full cursor-pointer perspective-1000 group"
          >
            <div
              className={cn(
                "absolute inset-0 w-full h-full rounded-3xl transition-transform duration-500 ease-out preserve-3d shadow-md border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-950",
                isFlipped && "rotate-y-180"
              )}
            >
              {/* CARD FRONT FACE */}
              <div className="absolute inset-0 w-full h-full p-8 flex flex-col justify-between backface-hidden">
                <Badge variant="outline" className="w-fit text-[9px] font-bold uppercase tracking-wider text-slate-400 pointer-events-none">
                  Front (Question / Term)
                </Badge>
                <div className="flex-1 flex items-center justify-center text-center">
                  <p className="text-base md:text-lg font-bold text-slate-800 dark:text-zinc-50 leading-relaxed font-mono">
                    {activeDeck.cards[currentCardIdx].front}
                  </p>
                </div>
                <div className="text-[10px] text-slate-400 dark:text-zinc-500 text-center flex items-center justify-center gap-1.5">
                  <HelpCircle className="h-3.5 w-3.5" />
                  Click card to flip and view explanation
                </div>
              </div>

              {/* CARD BACK FACE */}
              <div className="absolute inset-0 w-full h-full p-8 flex flex-col justify-between backface-hidden rotate-y-180">
                <Badge variant="outline" className="w-fit text-[9px] font-bold uppercase tracking-wider text-violet-500 border-violet-500/25 pointer-events-none">
                  Back (Explanation)
                </Badge>
                <div className="flex-1 flex items-center justify-center text-center overflow-y-auto">
                  <p className="text-sm md:text-base font-medium text-slate-700 dark:text-zinc-200 leading-relaxed whitespace-pre-wrap">
                    {activeDeck.cards[currentCardIdx].back}
                  </p>
                </div>
                {activeDeck.cards[currentCardIdx].sourceQuestion && (
                  <div className="p-2 rounded-xl bg-slate-50 dark:bg-zinc-900 border border-slate-100 dark:border-zinc-800/40 text-[9px] text-left text-slate-400 dark:text-zinc-500">
                    <span className="font-semibold text-violet-500">Derived from paper:</span> {activeDeck.cards[currentCardIdx].sourceQuestion}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Feedback & Actions */}
          <div className="flex justify-center gap-4 pt-4">
            {!isFlipped ? (
              <Button
                onClick={() => setIsFlipped(true)}
                className="h-12 px-8 rounded-xl bg-violet-600 hover:bg-violet-700 text-white font-medium shadow-md shadow-violet-500/10 flex items-center gap-2"
              >
                Reveal Answer
                <RefreshCw className="h-4 w-4 animate-spin-slow" />
              </Button>
            ) : (
              <div className="flex gap-4 w-full sm:w-auto">
                <Button
                  onClick={() => handleCardFeedback(false)}
                  className="flex-1 sm:flex-initial h-12 px-6 rounded-xl bg-red-500 hover:bg-red-600 text-white font-medium flex items-center justify-center gap-2"
                >
                  <X className="h-4 w-4" />
                  Need Practice
                </Button>
                <Button
                  onClick={() => handleCardFeedback(true)}
                  className="flex-1 sm:flex-initial h-12 px-6 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-white font-medium flex items-center justify-center gap-2"
                >
                  <Check className="h-4 w-4" />
                  I Know This!
                </Button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
